# Generated by Django 5.0.7 on 2024-07-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_remove_course_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_id",
            field=models.CharField(max_length=50),
        ),
    ]
