# Generated by Django 5.0.7 on 2024-08-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_course_course_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_name", models.CharField(max_length=250)),
                ("student_name", models.CharField(max_length=250)),
                ("contact_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=200)),
                ("joined_date", models.DateField()),
            ],
        ),
    ]
